image: 
- Visual Studio 2019
- Ubuntu1804

environment:
  major: 4
  minor: 1
  release: 0
  app_version: '$(major).$(minor).$(release).$(APPVEYOR_BUILD_NUMBER)'

version: '$(major).$(minor).$(release).{build}'

build_script:
  - cmd: msbuild OSPSuite.SimModelSolver.CVODES.sln /property:Configuration=Debug;Platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: msbuild OSPSuite.SimModelSolver.CVODES.sln /property:Configuration=Release;Platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  # linux specific cmake build of CVODES (C static lib) and OSPSuite.SimModelSolver_CVODES (C++ dynamic lib)
  - sh: cmake -BBuild/Release/x64/CVODE/ -Hsrc/CVODES/ -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_BUILD_TYPE=Release -DBUILD_ARKODE=OFF -DBUILD_CVODE=OFF -DBUILD_CVODES=ON -DBUILD_IDA=OFF -DBUILD_IDAS=OFF -DBUILD_KINSOL=OFF -DBUILD_SHARED_LIBS=OFF -DEXAMPLES_ENABLE_C=OFF -DBUILD_STATIC_LIBS=ON
  - sh: make -C Build/Release/x64/CVODE/
  - sh: cmake -BBuild/Debug/x64/CVODE/ -Hsrc/CVODES/ -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_BUILD_TYPE=Debug -DBUILD_ARKODE=OFF -DBUILD_CVODE=OFF -DBUILD_CVODES=ON -DBUILD_IDA=OFF -DBUILD_IDAS=OFF -DBUILD_KINSOL=OFF -DBUILD_SHARED_LIBS=OFF -DEXAMPLES_ENABLE_C=OFF -DBUILD_STATIC_LIBS=ON
  - sh: make -C Build/Debug/x64/CVODE/
  - sh: cmake -BBuild/Release/x64/ -Hsrc/OSPSuite.SimModelSolver_CVODES/ -DCMAKE_BUILD_TYPE=Release -DlibCVODES=Build/Release/x64/CVODE/src/cvodes/libsundials_cvodes.a
  - sh: make -C Build/Release/x64/
  - sh: cmake -BBuild/Debug/x64/ -Hsrc/OSPSuite.SimModelSolver_CVODES/ -DCMAKE_BUILD_TYPE=Debug -DlibCVODES=Build/Debug/x64/CVODE/src/cvodes/libsundials_cvodes.a
  - sh: make -C Build/Debug/x64/

cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

before_build:
  - ps: (get-content src\OSPSuite.SimModelSolver_CVODES\version.h) | foreach-object {$_ -replace "RELEASE 0", "RELEASE $env:RELEASE" -replace "MAJOR 0", "MAJOR $env:MAJOR" -replace "MINOR 0", "MINOR $env:MINOR" -replace "BUILD 0", "BUILD $env:APPVEYOR_BUILD_NUMBER"} | set-content src\OSPSuite.SimModelSolver_CVODES\version.h
  # nuget packages are required by tests only which is currently performed on Windows only
  - cmd: nuget sources add -name bddhelper -source https://ci.appveyor.com/nuget/ospsuite-bddhelper 
  - cmd: nuget install packages.config -OutputDirectory packages # cannot use automatic artifact publish because it's not recognized in a C++/CLI project

skip_branch_with_pr: true

skip_tags: true

branches:
  only:
    - master
    - develop

pull_requests: 
  do_not_increment_build_number: true     

install:
  - cmd: git submodule update --init --recursive
  - sh: git submodule update --init --recursive

after_build:
  - cmd: nuget pack src\OSPSuite.SimModelSolver_CVODES\OSPSuite.SimModelSolver_CVODES.nuspec -version %app_version%
  - sh: nuget pack src/OSPSuite.SimModelSolver_CVODES/OSPSuite.SimModelSolver_CVODES_Ubuntu18.nuspec -version $app_version
  - ps: Get-ChildItem .\OSPSuite.SimModelSolver_CVODES.*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  
test:
  # currently tests are run on Windows only
  assemblies:
  - '**\*.Tests.Release.x64.dll'
  
skip_commits:
  files:
    - '*.md'

nuget:
  disable_publish_on_pr: true

notifications:
  - provider: Slack
    incoming_webhook:      
      secure: 4MH9Em6TtrKalq6808dhPOqypTfYBJvVlqPaa9akNyF1h7st5qNdNezFp6T+bWXqrcZ4q/smtPcJ7LkUFHL46JDYUFlIL8FDz+ApX/vP+x0=  
